"""Initial tables

Revision ID: d63f0f928c05
Revises: 
Create Date: 2025-07-11 14:11:40.120237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63f0f928c05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politician',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('trades', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.String(), nullable=True),
    sa.Column('total_return', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_politician_id'), 'politician', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('alert_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('politician', sa.String(), nullable=True),
    sa.Column('email_frequency', sa.String(), nullable=False),
    sa.Column('enable_email', sa.Boolean(), nullable=True),
    sa.Column('notify_high_volume', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('notify_new_politician', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_setting_id'), 'alert_setting', ['id'], unique=False)
    op.create_table('following',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_following_id'), 'following', ['id'], unique=False)
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=True),
    sa.Column('politician', sa.String(), nullable=False),
    sa.Column('party', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('stock', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('current_price', sa.String(), nullable=True),
    sa.Column('return_', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_id'), 'trade', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_id'), table_name='trade')
    op.drop_table('trade')
    op.drop_index(op.f('ix_following_id'), table_name='following')
    op.drop_table('following')
    op.drop_index(op.f('ix_alert_setting_id'), table_name='alert_setting')
    op.drop_table('alert_setting')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_politician_id'), table_name='politician')
    op.drop_table('politician')
    # ### end Alembic commands ###
